title: "Hackin' Tasks Together"
description: ""
baseurl: "/"
url: "https://hackintasks.github.io"

logo: nes-kirby
show_downloads: false

paginate: 10

remote_theme: julianolf/jekyll-theme-8bit
permalink: /:title

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown

exclude: 
  - README.md
  - .gitignore

include: [_pages]